# 1. A URL com o nome do banco no final
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefa

# 2. Seu usuário do banco
# (Pela sua imagem anterior, parecia ser 'loidpadre' ou 'postgres', coloque o que você usou no DBeaver)
spring.datasource.username=loidpadre

# 3. Sua senha do banco
spring.datasource.password=

# 4. Configurações úteis do JPA/Hibernate
# Mostra no terminal os comandos SQL que o Spring rodar (ótimo para aprender)
spring.jpa.show-sql=true

# Cria as tabelas automaticamente quando você criar suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Ajusta o dialeto para o Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect